

build: boonela.buildrooms.c
	gcc -o build -g boonela.buildrooms.c

adventure: boonela.adventure.c
	gcc -o adventure -g boonela.adventure.c -lpthread

make: build adventure

clean: 
	rm -f build adventure
